name: project cicd flow
on: workflow_dispatch
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.8.2
      - name: Build with Maven
        run: mvn clean install
      - name: Github login
        run: |
          name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.GH_USERNAME }}
          password: ${{ secrets.GH_TOKEN }}
      - name: Build Docker image
        run: |
          docker build . -t ghcr.io/paduxe/helloworld-images:latest
      - name: Push Docker image
        run: |
          docker push ghcr.io/paduxe/helloworld-images:latest
      - name: Create mnt folder and run docker compose
        run: |
          mkdir -p /mnt/studydevops/
          mv docker-compose.yml /mnt/studydevops/
          pwd
          cd /mnt/studydevops/
          pwd
          ls -a
          docker ps
          docker-compose up -d
