name: project cicd flow
on: workflow_dispatch
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Build with Maven
        run: mvn clean install
      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          image-name: balo282/helloworld-images
          image-tag: latest