name: project cicd flow
on: workflow_dispatch
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        run: mvn clean install
      - name: Build & push Docker image
        run: |
          docker build . -t ghcr.io/paduxe/helloworld-images:latest
          docker push ghcr.io/balo282/helloworld-images:latest
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          image-name: paduxe/helloworld-images
          image-tag: latest