name: project cicd flow
on: workflow_dispatch
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Install curl (for nektos/act local CI testing)
        run: apt-get update && apt-get install build-essential curl pkg-config openssl -y
      - name: Download Maven
        run: |
          curl -sL https://www-eu.apache.org/dist/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.zip -o maven.zip
          apt-get update
          apt-get -y install unzip
          unzip -d /usr/share maven.zip
          rm maven.zip
          ln -s /usr/share/apache-maven-3.6.3/bin/mvn /usr/bin/mvn
          echo "M2_HOME=/usr/share/apache-maven-3.6.3" | tee -a /etc/environment
      - name: Build with Maven
        run: |
          whereis mvn
          whereis java
          mvn clean install
      - name: Github login
        run: |
          docker login --username balo282 --password ${{ secrets.GH_TOKEN }} ghcr.io
      - name: Build Docker image
        run: |
          docker build . -t ghcr.io/paduxe/helloworld-images:latest
      - name: Push Docker image
        run: |
          docker push ghcr.io/paduxe/helloworld-images:latest
      - name: Create mnt folder and run docker compose
        run: |
          mkdir /mnt/studydevops/
          mv docker-compose.yml /mnt/studydevops/
          docker ps
          docker-compose up -d
