name: project cicd flow
on: workflow_dispatch
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: setup jdk and maven
        run: |
           wget https://download.java.net/java/GA/jdk13.0.1/cec27d702aa74d5a8630c65ae61e4305/9/GPL/openjdk-13.0.1_linux-x64_bin.tar.gz
           tar -xvf openjdk-13.0.1_linux-x64_bin.tar.gz
           mv jdk-13.0.1 /opt/
           export JAVA_HOME='/opt/jdk-13.0.1'
           export PATH="$JAVA_HOME/bin:$PATH"
           export PATH
           wget https://mirrors.estointernet.in/apache/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz
           tar -xvf apache-maven-3.6.3-bin.tar.gz
           mv apache-maven-3.6.3 /opt/
           M2_HOME='/opt/apache-maven-3.6.3'
           PATH="$M2_HOME/bin:$PATH"
           export PATH
      - name: Build with Maven
        run: mvn clean install
      - name: Github login
        run: |
          docker login --username balo282 --password ${{ secrets.GH_TOKEN }} ghcr.io
      - name: Build Docker image
        run: |
          docker build . -t ghcr.io/paduxe/helloworld-images:latest
      - name: Push Docker image
        run: |
          docker push ghcr.io/paduxe/helloworld-images:latest
      - name: Create mnt folder and run docker compose
        run: |
          mkdir /mnt/studydevops/
          mv docker-compose.yml /mnt/studydevops/
          docker ps
          docker-compose up -d
