name: project cicd flow
on: workflow_dispatch
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Build with Maven
        run: mvn clean install
      - name: Github login
        run: |
          docker login --username balo282 --password ${{ secrets.GH_TOKEN }} ghcr.io
      - name: Build Docker image
        run: |
          docker build . -t ghcr.io/paduxe/helloworld-images:latest
      - name: Push Docker image
        run: |
          docker push ghcr.io/paduxe/helloworld-images:latest
      - name: Create mnt folder and run docker compose
        run: |
          mkdir /mnt/studydevops/
          mv docker-compose.yml /mnt/studydevops/
          docker ps
          docker-compose up -d
